### ISSUE TITLE
Is this project supported? (celo dependency)

### ISSUE THREAD

**Issue by aaronmgdr** [Alex-Neo-Projects/Coperacha-app#86]
Hi,

Im not sure if this is a supported app but i do see it is using a [deprecated version of celo contractkit.](https://github.com/Alex-Neo-Projects/Coperacha-app/blob/master/package.json#L12)

This version of contractkit only [supports transaction type](https://github.com/celo-org/txtypes?tab=readme-ov-file#scheduled-for-deprecation-on-celo) that will cease to function when celo completes its L2 transition.

The minimum supported version of contract kit is [@celo/contractkit@8.1.0](https://github.com/celo-org/developer-tooling/releases/tag/%40celo%2Fcontractkit%408.1.0)

I recommend upgrading within the next 3 months.

https://github.com/Alex-Neo-Projects/Coperacha-app/blob/2ba193a9ecd1c44df502c42e282c9f0604f5fe91/package.json#L12

**Comment by alexreyes** [comment]
Nope, it's not supported anymore. This was a project we made for a hackathon a few years ago but we haven't continued with it
